# Generated by Django 4.1 on 2022-08-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_deadline_news_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='deadline',
        ),
    ]
