# Generated by Django 4.1 on 2022-08-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_headline_news_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='deadline',
            new_name='headline',
        ),
    ]
