# Generated by Django 4.1 on 2022-08-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_deadline_news_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='deadline',
        ),
    ]
